apiVersion: redhat.com/v1alpha1
kind: AnsibleEE
metadata:
  name: ansibleee-role
  namespace: openstack
spec:
  # We can specify either 
  # - playbook: which will run with default ansible-runner options
  # - roles: which will run a list of tasks in files inside roles
  # - args: which allows specify the whole command that we want to execute
  roles:
    strategy: tripleo_free
    become: true
    tasks:
      - name: Generic standalone playbook running tripleo_podman | tripleo_podman_configure.yml | tripleo_podman
        import_role:
          name: tripleo_podman
          tasks_from: tripleo_podman_configure.yml
        tags:
          - tripleo_podman
      - name: Generic standalone playbook running tripleo_container_manage | shutdown.yml
        import_role:
          name: tripleo_container_manage
          tasks_from: shutdown.yml
      
  #args: ["ansible-runner", "run", "/runner", "-p", "standalone-playbook.yaml"]
  image: "quay.io/jlarriba/openstack-tripleo-ansible-ee"
  inventory: |
    Compute:
      hosts:
        compute-0:
          ansible_host: 10.0.0.4
      vars:
        ansible_ssh_user: root
    allovercloud:
      children:
        Compute:
    overcloud:
      children:
        Compute:
  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_SSH_ARGS
      value: "-C -o ControlMaster=auto -o ControlPersist=80s"
    - name: ANSIBLE_ENABLE_TASK_DEBUGGER
      value: "True"
  configs:
    - name: swift-configmap
      mountpath: /runner/configs/swift-configmap
    - name: test-configmap-1
      mountpath: /runner/configs/test-configmap-1
    - name: test-configmap-2
      mountpath: /runner/configs/test-configmap-2